-- Add complete learning content for Frontend Developer role
-- First, find or create the Frontend Developer role
DO $$
DECLARE
  frontend_role_id uuid;
  frontend_path_id uuid;
  html_course_id uuid;
  css_course_id uuid;
  js_course_id uuid;
  react_course_id uuid;
  project_course_id uuid;
BEGIN
  -- Get Frontend Developer role
  SELECT id INTO frontend_role_id FROM career_roles WHERE slug = 'frontend-developer' LIMIT 1;
  
  -- If no frontend developer role exists, create one
  IF frontend_role_id IS NULL THEN
    INSERT INTO career_roles (title, slug, category, description, salary_min_inr, salary_max_inr, demand_level, growth_outlook, day_in_life)
    VALUES (
      'Frontend Developer',
      'frontend-developer', 
      'engineering',
      'Build beautiful, responsive user interfaces using modern web technologies like React, TypeScript, and CSS frameworks.',
      400000,
      2500000,
      'Very High',
      'Frontend development continues to grow with increasing demand for interactive web applications and mobile-first experiences.',
      'A typical day involves collaborating with designers to implement UI components, writing clean React code, debugging browser issues, and participating in code reviews.'
    )
    RETURNING id INTO frontend_role_id;
  END IF;

  -- Create or get learning path
  SELECT id INTO frontend_path_id FROM learning_paths WHERE role_id = frontend_role_id LIMIT 1;
  
  IF frontend_path_id IS NULL THEN
    INSERT INTO learning_paths (role_id, title, description, difficulty_level, estimated_hours)
    VALUES (
      frontend_role_id,
      'Frontend Developer Mastery',
      'Complete learning path to become a job-ready Frontend Developer. Master HTML, CSS, JavaScript, and React.',
      'beginner',
      120
    )
    RETURNING id INTO frontend_path_id;
  ELSE
    -- Clear existing courses and lessons for fresh content
    DELETE FROM lessons WHERE course_id IN (SELECT id FROM courses WHERE learning_path_id = frontend_path_id);
    DELETE FROM courses WHERE learning_path_id = frontend_path_id;
  END IF;

  -- Course 1: HTML Fundamentals
  INSERT INTO courses (learning_path_id, title, description, order_index, estimated_hours)
  VALUES (frontend_path_id, 'HTML Fundamentals', 'Learn the building blocks of web pages', 0, 8)
  RETURNING id INTO html_course_id;

  INSERT INTO lessons (course_id, title, content, lesson_type, order_index, estimated_minutes) VALUES
  (html_course_id, 'Introduction to HTML', E'# What is HTML?\n\nHTML (HyperText Markup Language) is the standard markup language for creating web pages. It describes the structure of a web page using elements or "tags".\n\n## Key Concepts\n\n1. **Elements**: Building blocks like <div>, <p>, <h1>\n2. **Attributes**: Additional information like class, id, src\n3. **Nesting**: Elements can contain other elements\n\n## Your First HTML\n\n```html\n<!DOCTYPE html>\n<html>\n  <head>\n    <title>My First Page</title>\n  </head>\n  <body>\n    <h1>Hello World!</h1>\n  </body>\n</html>\n```\n\nEvery HTML document starts with `<!DOCTYPE html>` declaration and has `<html>`, `<head>`, and `<body>` sections.', 'reading', 0, 15),
  (html_course_id, 'HTML Elements & Tags', E'# Common HTML Elements\n\n## Headings\nHTML has 6 heading levels:\n```html\n<h1>Main Heading</h1>\n<h2>Subheading</h2>\n<h3>Sub-subheading</h3>\n```\n\n## Paragraphs & Text\n```html\n<p>This is a paragraph.</p>\n<strong>Bold text</strong>\n<em>Italic text</em>\n```\n\n## Lists\n```html\n<ul>\n  <li>Unordered item</li>\n</ul>\n<ol>\n  <li>Ordered item</li>\n</ol>\n```\n\n## Links & Images\n```html\n<a href="https://example.com">Click me</a>\n<img src="photo.jpg" alt="Description">\n```', 'reading', 1, 20),
  (html_course_id, 'Practice: Build a Profile Page', E'# Coding Exercise: Build Your Profile\n\n## Challenge\nCreate a personal profile page with:\n- Your name as h1\n- A short bio paragraph\n- A list of 3 skills\n- A link to your favorite website\n\n## Starter Code\n```html\n<!DOCTYPE html>\n<html>\n<head>\n  <title>My Profile</title>\n</head>\n<body>\n  <!-- Add your code here -->\n  \n</body>\n</html>\n```\n\n## Expected Output\nYour page should display your name, bio, skills list, and a clickable link.', 'coding', 2, 25),
  (html_course_id, 'Semantic HTML', E'# Semantic HTML5 Elements\n\nSemantic elements clearly describe their meaning to both the browser and developer.\n\n## Key Semantic Elements\n\n```html\n<header>Site header content</header>\n<nav>Navigation links</nav>\n<main>Main page content</main>\n<article>Self-contained content</article>\n<section>Thematic grouping</section>\n<aside>Sidebar content</aside>\n<footer>Footer information</footer>\n```\n\n## Why Semantic HTML?\n1. **Accessibility**: Screen readers understand page structure\n2. **SEO**: Search engines better index content\n3. **Maintainability**: Code is easier to read\n\n## Example Structure\n```html\n<body>\n  <header>\n    <nav>...</nav>\n  </header>\n  <main>\n    <article>...</article>\n  </main>\n  <footer>...</footer>\n</body>\n```', 'reading', 3, 20),
  (html_course_id, 'Forms & Input Elements', E'# HTML Forms\n\nForms collect user input and send it to a server.\n\n## Basic Form Structure\n```html\n<form action="/submit" method="POST">\n  <label for="name">Name:</label>\n  <input type="text" id="name" name="name" required>\n  \n  <label for="email">Email:</label>\n  <input type="email" id="email" name="email">\n  \n  <button type="submit">Submit</button>\n</form>\n```\n\n## Input Types\n- `text` - Single line text\n- `email` - Email validation\n- `password` - Hidden input\n- `number` - Numeric input\n- `checkbox` - Multiple selections\n- `radio` - Single selection\n- `date` - Date picker\n\n## Other Form Elements\n```html\n<textarea rows="4">Long text...</textarea>\n<select>\n  <option value="1">Option 1</option>\n</select>\n```', 'reading', 4, 25),
  (html_course_id, 'Quiz: HTML Basics', E'# HTML Quiz\n\nTest your HTML knowledge!\n\n## Question 1\nWhat tag is used for the largest heading?\na) <heading>\nb) <h1>\nc) <head>\nd) <title>\n\n## Question 2\nWhich attribute makes a form field required?\na) must\nb) needed\nc) required\nd) validate\n\n## Question 3\nWhat is the correct HTML for a hyperlink?\na) <link href="url">Text</link>\nb) <a url="url">Text</a>\nc) <a href="url">Text</a>\nd) <hyperlink>Text</hyperlink>\n\n## Question 4\nWhich semantic element represents the main content?\na) <content>\nb) <body>\nc) <main>\nd) <article>', 'quiz', 5, 15);

  -- Course 2: CSS Styling
  INSERT INTO courses (learning_path_id, title, description, order_index, estimated_hours)
  VALUES (frontend_path_id, 'CSS Styling', 'Style your web pages beautifully', 1, 15)
  RETURNING id INTO css_course_id;

  INSERT INTO lessons (course_id, title, content, lesson_type, order_index, estimated_minutes) VALUES
  (css_course_id, 'Introduction to CSS', E'# What is CSS?\n\nCSS (Cascading Style Sheets) controls how HTML elements look on screen.\n\n## Three Ways to Add CSS\n\n1. **Inline**: `<p style="color: red;">Text</p>`\n2. **Internal**: `<style>` tag in head\n3. **External**: Separate .css file (recommended)\n\n## CSS Syntax\n```css\nselector {\n  property: value;\n}\n\nh1 {\n  color: blue;\n  font-size: 24px;\n}\n```\n\n## Selectors\n- `element` - Selects all elements\n- `.class` - Selects by class\n- `#id` - Selects by ID\n- `element.class` - Combined', 'reading', 0, 20),
  (css_course_id, 'Colors, Fonts & Text', E'# Styling Text with CSS\n\n## Colors\n```css\n/* Different color formats */\ncolor: red;\ncolor: #ff0000;\ncolor: rgb(255, 0, 0);\ncolor: hsl(0, 100%, 50%);\nbackground-color: #f0f0f0;\n```\n\n## Fonts\n```css\nfont-family: "Arial", sans-serif;\nfont-size: 16px;\nfont-weight: bold; /* or 400, 700 */\nfont-style: italic;\n```\n\n## Text Properties\n```css\ntext-align: center;\ntext-decoration: underline;\ntext-transform: uppercase;\nline-height: 1.5;\nletter-spacing: 2px;\n```\n\n## Google Fonts\n```html\n<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">\n```\n```css\nbody {\n  font-family: "Roboto", sans-serif;\n}\n```', 'reading', 1, 25),
  (css_course_id, 'Box Model & Layout', E'# The CSS Box Model\n\nEvery element is a box with:\n- **Content**: The actual content\n- **Padding**: Space inside border\n- **Border**: Edge of element\n- **Margin**: Space outside border\n\n```css\n.box {\n  width: 200px;\n  height: 100px;\n  padding: 20px;\n  border: 2px solid black;\n  margin: 10px;\n}\n```\n\n## Box Sizing\n```css\n* {\n  box-sizing: border-box; /* Include padding in width */\n}\n```\n\n## Display Property\n```css\ndisplay: block;       /* Full width */\ndisplay: inline;      /* Inline with text */\ndisplay: inline-block; /* Inline but can set width/height */\ndisplay: none;        /* Hidden */\n```', 'reading', 2, 30),
  (css_course_id, 'Flexbox Layout', E'# CSS Flexbox\n\nFlexbox is a one-dimensional layout method for arranging items.\n\n## Container Properties\n```css\n.container {\n  display: flex;\n  flex-direction: row; /* row, column */\n  justify-content: center; /* main axis */\n  align-items: center; /* cross axis */\n  gap: 20px;\n}\n```\n\n## Justify Content Values\n- `flex-start` - Items at start\n- `flex-end` - Items at end\n- `center` - Items centered\n- `space-between` - Equal space between\n- `space-around` - Equal space around\n\n## Item Properties\n```css\n.item {\n  flex: 1; /* Grow to fill space */\n  flex-grow: 1;\n  flex-shrink: 0;\n  align-self: flex-end;\n}\n```\n\n## Common Pattern: Centered Content\n```css\n.centered {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  min-height: 100vh;\n}\n```', 'reading', 3, 35),
  (css_course_id, 'Practice: Style a Card Component', E'# Coding Exercise: Style a Card\n\n## Challenge\nCreate a styled card component with:\n- Rounded corners\n- Shadow effect\n- Image at top\n- Title and description\n- A button at bottom\n\n## Starter Code\n```html\n<div class="card">\n  <img src="https://via.placeholder.com/300x150" alt="Card image">\n  <div class="card-content">\n    <h3>Card Title</h3>\n    <p>This is a description of the card.</p>\n    <button>Learn More</button>\n  </div>\n</div>\n```\n\n```css\n.card {\n  /* Add your styles */\n}\n```\n\n## Tips\n- Use `border-radius` for rounded corners\n- Use `box-shadow` for depth\n- Use flexbox for layout', 'coding', 4, 40),
  (css_course_id, 'CSS Grid', E'# CSS Grid Layout\n\nGrid is a two-dimensional layout system.\n\n## Basic Grid\n```css\n.grid-container {\n  display: grid;\n  grid-template-columns: 1fr 1fr 1fr; /* 3 equal columns */\n  grid-template-rows: 100px 200px;\n  gap: 20px;\n}\n```\n\n## Grid Template Areas\n```css\n.layout {\n  display: grid;\n  grid-template-areas:\n    "header header"\n    "sidebar main"\n    "footer footer";\n  grid-template-columns: 200px 1fr;\n}\n\n.header { grid-area: header; }\n.sidebar { grid-area: sidebar; }\n.main { grid-area: main; }\n```\n\n## Responsive Grid\n```css\n.grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n  gap: 1rem;\n}\n```', 'reading', 5, 30),
  (css_course_id, 'Responsive Design', E'# Responsive Web Design\n\nMake your site work on all screen sizes.\n\n## Viewport Meta Tag\n```html\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n```\n\n## Media Queries\n```css\n/* Mobile first approach */\n.container {\n  padding: 10px;\n}\n\n/* Tablet */\n@media (min-width: 768px) {\n  .container {\n    padding: 20px;\n  }\n}\n\n/* Desktop */\n@media (min-width: 1024px) {\n  .container {\n    padding: 40px;\n    max-width: 1200px;\n    margin: 0 auto;\n  }\n}\n```\n\n## Responsive Units\n- `%` - Percentage of parent\n- `vw/vh` - Viewport width/height\n- `rem` - Relative to root font size\n- `em` - Relative to parent font size', 'reading', 6, 25);

  -- Course 3: JavaScript Essentials
  INSERT INTO courses (learning_path_id, title, description, order_index, estimated_hours)
  VALUES (frontend_path_id, 'JavaScript Essentials', 'Add interactivity to your websites', 2, 25)
  RETURNING id INTO js_course_id;

  INSERT INTO lessons (course_id, title, content, lesson_type, order_index, estimated_minutes) VALUES
  (js_course_id, 'Introduction to JavaScript', E'# What is JavaScript?\n\nJavaScript is the programming language of the web. It makes pages interactive.\n\n## Adding JavaScript\n```html\n<!-- Inline -->\n<button onclick="alert(''Hello!'')">Click</button>\n\n<!-- Internal -->\n<script>\n  console.log("Hello World");\n</script>\n\n<!-- External (recommended) -->\n<script src="script.js"></script>\n```\n\n## Variables\n```javascript\n// Modern way (recommended)\nlet name = "John";      // Can be reassigned\nconst age = 25;         // Cannot be reassigned\n\n// Old way (avoid)\nvar oldWay = "deprecated";\n```\n\n## Data Types\n- String: `"Hello"`\n- Number: `42`, `3.14`\n- Boolean: `true`, `false`\n- Array: `[1, 2, 3]`\n- Object: `{ name: "John" }`\n- null, undefined', 'reading', 0, 25),
  (js_course_id, 'Functions & Scope', E'# JavaScript Functions\n\n## Function Declaration\n```javascript\nfunction greet(name) {\n  return "Hello, " + name;\n}\n\ngreet("Alice"); // "Hello, Alice"\n```\n\n## Arrow Functions (ES6+)\n```javascript\nconst greet = (name) => {\n  return `Hello, ${name}`;\n};\n\n// Short form for single expression\nconst double = x => x * 2;\n```\n\n## Scope\n```javascript\nlet global = "I am global";\n\nfunction example() {\n  let local = "I am local";\n  console.log(global); // Works\n  console.log(local);  // Works\n}\n\nconsole.log(local); // Error! Not defined\n```\n\n## Template Literals\n```javascript\nconst name = "Alice";\nconst message = `Hello, ${name}!`; // Use backticks\n```', 'reading', 1, 30),
  (js_course_id, 'Arrays & Objects', E'# Arrays & Objects\n\n## Arrays\n```javascript\nconst fruits = ["apple", "banana", "orange"];\n\nfruits.push("grape");     // Add to end\nfruits.pop();             // Remove from end\nfruits.length;            // 3\nfruits[0];                // "apple"\n\n// Array methods\nfruits.map(f => f.toUpperCase());\nfruits.filter(f => f.length > 5);\nfruits.find(f => f === "banana");\nfruits.forEach(f => console.log(f));\n```\n\n## Objects\n```javascript\nconst person = {\n  name: "Alice",\n  age: 25,\n  skills: ["JS", "React"],\n  greet() {\n    return `Hi, I am ${this.name}`;\n  }\n};\n\nperson.name;      // "Alice"\nperson["age"];    // 25\nperson.greet();   // "Hi, I am Alice"\n```\n\n## Destructuring\n```javascript\nconst { name, age } = person;\nconst [first, second] = fruits;\n```', 'reading', 2, 35),
  (js_course_id, 'Practice: Array Methods', E'# Coding Exercise: Array Methods\n\n## Challenge\nGiven an array of numbers, write functions to:\n1. Double all numbers\n2. Filter only even numbers\n3. Find the sum of all numbers\n4. Find the maximum number\n\n## Starter Code\n```javascript\nconst numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n\n// 1. Double all numbers using map\nfunction doubleAll(arr) {\n  // Your code here\n}\n\n// 2. Filter even numbers\nfunction getEvens(arr) {\n  // Your code here\n}\n\n// 3. Sum all numbers using reduce\nfunction getSum(arr) {\n  // Your code here\n}\n\n// 4. Find maximum\nfunction getMax(arr) {\n  // Your code here\n}\n\n// Test your functions\nconsole.log(doubleAll(numbers));\nconsole.log(getEvens(numbers));\nconsole.log(getSum(numbers));\nconsole.log(getMax(numbers));\n```', 'coding', 3, 40),
  (js_course_id, 'DOM Manipulation', E'# The Document Object Model\n\nThe DOM is how JavaScript interacts with HTML.\n\n## Selecting Elements\n```javascript\n// By ID\nconst header = document.getElementById("header");\n\n// By class (returns collection)\nconst items = document.getElementsByClassName("item");\n\n// Modern way (recommended)\nconst element = document.querySelector(".class");\nconst elements = document.querySelectorAll("p");\n```\n\n## Modifying Elements\n```javascript\nelement.textContent = "New text";\nelement.innerHTML = "<strong>Bold</strong>";\nelement.style.color = "red";\nelement.classList.add("active");\nelement.classList.remove("hidden");\nelement.classList.toggle("visible");\n```\n\n## Event Listeners\n```javascript\nconst button = document.querySelector("button");\n\nbutton.addEventListener("click", () => {\n  alert("Button clicked!");\n});\n\n// Common events: click, submit, keydown, mouseover\n```', 'reading', 4, 35),
  (js_course_id, 'Async JavaScript', E'# Asynchronous JavaScript\n\n## Callbacks\n```javascript\nsetTimeout(() => {\n  console.log("Delayed by 1 second");\n}, 1000);\n```\n\n## Promises\n```javascript\nconst promise = new Promise((resolve, reject) => {\n  // Async operation\n  if (success) {\n    resolve(data);\n  } else {\n    reject(error);\n  }\n});\n\npromise\n  .then(data => console.log(data))\n  .catch(error => console.error(error));\n```\n\n## Async/Await (Modern way)\n```javascript\nasync function fetchData() {\n  try {\n    const response = await fetch("/api/data");\n    const data = await response.json();\n    return data;\n  } catch (error) {\n    console.error(error);\n  }\n}\n```\n\n## Fetch API\n```javascript\nfetch("https://api.example.com/users")\n  .then(res => res.json())\n  .then(users => console.log(users));\n```', 'reading', 5, 40);

  -- Course 4: React Fundamentals
  INSERT INTO courses (learning_path_id, title, description, order_index, estimated_hours)
  VALUES (frontend_path_id, 'React Fundamentals', 'Build modern UIs with React', 3, 35)
  RETURNING id INTO react_course_id;

  INSERT INTO lessons (course_id, title, content, lesson_type, order_index, estimated_minutes) VALUES
  (react_course_id, 'Introduction to React', E'# What is React?\n\nReact is a JavaScript library for building user interfaces.\n\n## Why React?\n1. **Component-Based**: Build encapsulated components\n2. **Declarative**: Describe what you want, React handles how\n3. **Virtual DOM**: Efficient updates\n4. **Large Ecosystem**: Huge community and tools\n\n## JSX\nJSX lets you write HTML-like code in JavaScript:\n```jsx\nconst element = <h1>Hello, World!</h1>;\n\n// With expressions\nconst name = "Alice";\nconst greeting = <h1>Hello, {name}!</h1>;\n```\n\n## Your First Component\n```jsx\nfunction Welcome() {\n  return (\n    <div>\n      <h1>Welcome to React!</h1>\n      <p>This is a component.</p>\n    </div>\n  );\n}\n\nexport default Welcome;\n```', 'reading', 0, 30),
  (react_course_id, 'Components & Props', E'# React Components\n\n## Function Components\n```jsx\nfunction UserCard({ name, email, avatar }) {\n  return (\n    <div className="card">\n      <img src={avatar} alt={name} />\n      <h3>{name}</h3>\n      <p>{email}</p>\n    </div>\n  );\n}\n```\n\n## Using Components\n```jsx\nfunction App() {\n  return (\n    <div>\n      <UserCard \n        name="Alice" \n        email="alice@email.com"\n        avatar="/alice.jpg"\n      />\n      <UserCard \n        name="Bob" \n        email="bob@email.com"\n        avatar="/bob.jpg"\n      />\n    </div>\n  );\n}\n```\n\n## Props with Children\n```jsx\nfunction Container({ children, title }) {\n  return (\n    <div className="container">\n      <h2>{title}</h2>\n      {children}\n    </div>\n  );\n}\n\n// Usage\n<Container title="Users">\n  <UserCard name="Alice" />\n</Container>\n```', 'reading', 1, 35),
  (react_course_id, 'useState Hook', E'# State with useState\n\nState is data that changes over time in your component.\n\n## Basic useState\n```jsx\nimport { useState } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>\n        Increment\n      </button>\n    </div>\n  );\n}\n```\n\n## State with Objects\n```jsx\nfunction Form() {\n  const [form, setForm] = useState({\n    name: "",\n    email: ""\n  });\n\n  const handleChange = (e) => {\n    setForm({\n      ...form,\n      [e.target.name]: e.target.value\n    });\n  };\n\n  return (\n    <form>\n      <input \n        name="name"\n        value={form.name}\n        onChange={handleChange}\n      />\n    </form>\n  );\n}\n```', 'reading', 2, 40),
  (react_course_id, 'Practice: Build a Todo App', E'# Coding Exercise: Todo List\n\n## Challenge\nBuild a simple todo app with:\n- Input to add new todos\n- List of todos\n- Button to mark complete\n- Button to delete\n\n## Starter Code\n```jsx\nimport { useState } from "react";\n\nfunction TodoApp() {\n  const [todos, setTodos] = useState([]);\n  const [input, setInput] = useState("");\n\n  const addTodo = () => {\n    // Add new todo to list\n  };\n\n  const toggleComplete = (id) => {\n    // Mark todo as complete/incomplete\n  };\n\n  const deleteTodo = (id) => {\n    // Remove todo from list\n  };\n\n  return (\n    <div>\n      <h1>Todo App</h1>\n      <input \n        value={input}\n        onChange={(e) => setInput(e.target.value)}\n        placeholder="Add a todo..."\n      />\n      <button onClick={addTodo}>Add</button>\n      \n      <ul>\n        {/* Map through todos and render */}\n      </ul>\n    </div>\n  );\n}\n```', 'coding', 3, 60),
  (react_course_id, 'useEffect Hook', E'# Side Effects with useEffect\n\nuseEffect handles side effects like API calls, subscriptions, and DOM updates.\n\n## Basic useEffect\n```jsx\nimport { useState, useEffect } from "react";\n\nfunction UserProfile({ userId }) {\n  const [user, setUser] = useState(null);\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    // Runs after component mounts\n    fetch(`/api/users/${userId}`)\n      .then(res => res.json())\n      .then(data => {\n        setUser(data);\n        setLoading(false);\n      });\n  }, [userId]); // Dependency array\n\n  if (loading) return <p>Loading...</p>;\n  return <h1>{user.name}</h1>;\n}\n```\n\n## Cleanup Function\n```jsx\nuseEffect(() => {\n  const timer = setInterval(() => {\n    console.log("Tick");\n  }, 1000);\n\n  // Cleanup runs before unmount\n  return () => clearInterval(timer);\n}, []);\n```', 'reading', 4, 45),
  (react_course_id, 'Conditional Rendering & Lists', E'# Rendering Patterns\n\n## Conditional Rendering\n```jsx\nfunction Greeting({ isLoggedIn }) {\n  // Using ternary\n  return isLoggedIn ? <h1>Welcome back!</h1> : <h1>Please log in</h1>;\n}\n\n// Using &&\nfunction Notification({ count }) {\n  return (\n    <div>\n      {count > 0 && (\n        <span className="badge">{count}</span>\n      )}\n    </div>\n  );\n}\n```\n\n## Rendering Lists\n```jsx\nfunction UserList({ users }) {\n  return (\n    <ul>\n      {users.map((user) => (\n        <li key={user.id}>\n          {user.name} - {user.email}\n        </li>\n      ))}\n    </ul>\n  );\n}\n```\n\n## Key Prop\nAlways provide a unique `key` when rendering lists. Use IDs, not array indexes:\n```jsx\n{items.map((item) => <Item key={item.id} {...item} />)}\n```', 'reading', 5, 30),
  (react_course_id, 'Forms in React', E'# Handling Forms\n\n## Controlled Components\n```jsx\nfunction LoginForm() {\n  const [email, setEmail] = useState("");\n  const [password, setPassword] = useState("");\n\n  const handleSubmit = (e) => {\n    e.preventDefault();\n    console.log({ email, password });\n    // Submit to API\n  };\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input\n        type="email"\n        value={email}\n        onChange={(e) => setEmail(e.target.value)}\n        placeholder="Email"\n      />\n      <input\n        type="password"\n        value={password}\n        onChange={(e) => setPassword(e.target.value)}\n        placeholder="Password"\n      />\n      <button type="submit">Login</button>\n    </form>\n  );\n}\n```\n\n## Form Validation\n```jsx\nconst [errors, setErrors] = useState({});\n\nconst validate = () => {\n  const newErrors = {};\n  if (!email) newErrors.email = "Email required";\n  if (!password) newErrors.password = "Password required";\n  setErrors(newErrors);\n  return Object.keys(newErrors).length === 0;\n};\n```', 'reading', 6, 40);

  -- Course 5: Final Project
  INSERT INTO courses (learning_path_id, title, description, order_index, estimated_hours)
  VALUES (frontend_path_id, 'Capstone Project', 'Build a complete portfolio project', 4, 20)
  RETURNING id INTO project_course_id;

  INSERT INTO lessons (course_id, title, content, lesson_type, order_index, estimated_minutes) VALUES
  (project_course_id, 'Project: Personal Portfolio', E'# Capstone: Build Your Portfolio\n\n## Overview\nBuild a personal portfolio website showcasing your skills and projects.\n\n## Requirements\n1. **Hero Section**: Name, title, and intro\n2. **About Section**: Bio and skills\n3. **Projects Section**: At least 3 projects with images\n4. **Contact Form**: Working contact form\n5. **Responsive Design**: Works on mobile\n\n## Tech Stack\n- React for UI\n- CSS/Tailwind for styling\n- Responsive design\n\n## Structure\n```\nsrc/\n  components/\n    Navbar.jsx\n    Hero.jsx\n    About.jsx\n    Projects.jsx\n    Contact.jsx\n    Footer.jsx\n  App.jsx\n```\n\n## Tips\n- Start with mobile design first\n- Use CSS Grid or Flexbox for layouts\n- Add smooth scroll navigation\n- Include hover animations', 'coding', 0, 120),
  (project_course_id, 'Project Review & Certification', E'# Project Submission\n\n## Checklist\n\nBefore submitting, ensure your portfolio has:\n\n- [ ] Responsive design (mobile, tablet, desktop)\n- [ ] Clean, semantic HTML structure\n- [ ] Consistent styling and color scheme\n- [ ] At least 3 project showcases\n- [ ] Working navigation\n- [ ] Contact section\n- [ ] No console errors\n- [ ] Fast loading performance\n\n## Congratulations!\n\nYou have completed the Frontend Developer learning path!\n\nYou now know:\n- HTML5 & Semantic markup\n- CSS3, Flexbox & Grid\n- Responsive design principles\n- JavaScript ES6+\n- React fundamentals\n- Building real projects\n\n## Next Steps\n1. Deploy your portfolio (Vercel, Netlify)\n2. Add more projects as you build\n3. Learn TypeScript\n4. Explore state management (Redux, Zustand)\n5. Study backend basics\n\n🎓 Claim your certificate!', 'reading', 1, 30);

END $$;